name: release
on:
  push:
    branches:
      - main

env:
  RELEASE_PLZ_BIN_URL: https://github.com/MarcoIeni/release-plz/releases/download/release-plz-v0.3.11/release-plz-x86_64-unknown-linux-gnu.tar.gz

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'chore(release):')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          token: ${{ secrets.RELEASE_PAT }}
      - name: configure git for release
        shell: bash
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      # It's possible to `cargo install` these tools, but it's very slow to compile on GHA infra.
      # Therefore we just pull some binaries from the Github Releases.
      - name: install tools
        shell: bash
        run: |
          curl -L -O $RELEASE_PLZ_BIN_URL
          tar xvf release-plz-x86_64-unknown-linux-gnu.tar.gz
          rm release-plz-x86_64-unknown-linux-gnu.tar.gz
          sudo mv release-plz /usr/local/bin
      - name: publish and release
        shell: bash
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          release-plz release --git-token ${{ secrets.RELEASE_PAT }}
